# -*- coding: utf-8 -*-
"""IS.food_review.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XMUtnwqRoLcIF4PkJ2txvS4At2PNcewc
"""

import pandas as pd
import numpy as np

# Dataset 1
data1 = {
    'ID': range(1, 26),
    'Cuisine': ['Italian', 'Thai', 'Japanese', 'Fast Food', np.nan, 'Cafe', 'Shabu', 'Thaai', 'Japanese', 'Street Food',
                'Italian', 'Chinese', 'Steak', 'Bakery', 'Thai', 'Indian', 'Japanese', 'Fast Food', 'Korean', 'Vegan',
                'Cafe', 'Seafood', 'Thai', 'Buffet', 'Chinese'],
    'Avg_Price': [550, 150, 1200, 100, 2000, 120, '500+', 80, 1500, 50,
                  600, 450, 800, np.nan, 200, 350, 2500, 120, 499, 300,
                  95, 1200, 60, 799, 1000],
    'Location_Score': [8.5, np.nan, 9.2, 2.1, 4.5, 7.8, 3.0, 6.5, 8.9, np.nan,
                       7.5, 5.5, 3.2, 8.0, 2.5, 6.8, 9.5, 3.5, 7.2, 2.0,
                       8.2, 4.8, 7.0, 3.8, 8.7],
    'Social_Checkin': [1200, 450, 3500, 50, 100, 1500, 200, 800, 4200, np.nan,
                       1100, 600, 150, 2000, 80, 950, 5000, 300, 1300, 40,
                       1800, 400, 750, 250, 2800],
    'Status': [1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1]
}

df1 = pd.DataFrame(data1)
df1.to_csv('restaurant_data.csv', index=False)

import pandas as pd
import numpy as np

# Dataset 2
data2 = {
    'Review': [
        "อร่อยแสงออกปากกกก! 🌟🌟🌟 คุ้มค่าที่รอคอย", "เค็มจนไตสั่น กินน้ำตาม 3 ลิตร ไม่ไหวจริง",
        "เฉยๆ อะ พนง. บริการแย่มากกก", "ดีงามพระรามแปด คุ้มค่าสุดๆ มาซ้ำแน่นอน",
        "รอนานจนลูกบวช ห่วยแตก สกปรก", "รสชาติกลมกล่อม บริการประทับใจจจจ ❤️",
        "แพงแต่ไม่อร่อย เสียดายตังค์สุดๆ", "ร้านสวยมาก ถ่ายรูปปัง รสชาติจึ้งสุด",
        "หมูเหนียวเหมือนเคี้ยวหนังยาง ผิดหวังครับ", "นัวมากแม่ ปลาร้าคือที่สุดดดดด 🐟",
        "แมลงสาบวิ่งเล่นในร้าน บายจ้าาา", "คุ้มค่าเงินที่จ่ายไป แนะนำเลยร้านนี้",
        "พนักงานหน้าบูดเหมือนไปขอกินฟรี", "ไก่ทอดกรอบนอกนุ่มใน ฟินระดับสิบ",
        "จืดสนิทเหมือนลืมใส่น้ำปลา แย่ๆ", "บรรยากาศดี เพลงเพราะ อาหารอร่อย 10/10",
        "ให้น้อยเหมือนให้ชิม ไม่อิ่มเลยยย", "วัตถุดิบพรีเมียม สดใหม่มาก ชอบบ",
        "กลิ่นเหม็นอับในร้าน ทำให้อาหารไม่อร่อย", "เจ้าของร้านใจดี แถมขนมหวานให้ด้วย ✨",
        "รออาหารชั่วโมงครึ่ง โมโหหิวมาก", "ซุปหอมละมุนลิ้น กินแล้วหยุดไม่ได้",
        "น้ำจิ้มเปรี้ยวโดด ไม่กลมกล่อมเลย", "เครื่องเทศถึงใจ จัดจ้านในย่านนี้",
        "จานชามไม่สะอาด มีคราบมันติดอยู่"
    ],
    'Sentiment': [1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
}

df2 = pd.DataFrame(data2)
df2.to_csv('food_reviews.csv', index=False, encoding='utf-8-sig')

from sklearn.preprocessing import LabelEncoder

# ลบเครื่องหมาย + และเปลี่ยนราคาให้เป็นตัวเลข
df1['Avg_Price'] = df1['Avg_Price'].astype(str).str.replace('+', '', regex=False)
df1['Avg_Price'] = pd.to_numeric(df1['Avg_Price'], errors='coerce')

# เติมค่าว่าง Avg_Price ด้วยค่ามัธยฐาน
df1['Avg_Price'] = df1['Avg_Price'].fillna(df1['Avg_Price'].median())

# เติมค่าว่าง Location_Score ด้วยค่าเฉลี่ย
df1['Location_Score'] = df1['Location_Score'].fillna(df1['Location_Score'].mean())

# เติมค่าว่าง Social_Checkin ด้วย 0
df1['Social_Checkin'] = df1['Social_Checkin'].fillna(0)

# แปลงชื่อประเภทอาหารให้เป็นตัวเลข (Encoding)
le = LabelEncoder()
df1['Cuisine'] = le.fit_transform(df1['Cuisine'].astype(str))

# ตรวจสอบจำนวนค่าว่างคงเหลือ
print(df1.isnull().sum())
df1.head()

!pip install pythainlp

from pythainlp.tokenize import word_tokenize
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# ฟังก์ชันตัดคำไทยและลบช่องว่างออก
def tokenize_text(text):
    return [t for t in word_tokenize(text, engine='newmm') if t.strip()]

# เตรียม Tokenizer เพื่อแปลงคำเป็นตัวเลข
tokenizer = Tokenizer()
tokenizer.fit_on_texts(df2['Review'].apply(tokenize_text))

# แปลงประโยคเป็นลำดับตัวเลข
sequences = tokenizer.texts_to_sequences(df2['Review'].apply(tokenize_text))

# ทำ Padding ให้ทุกรีวิวยาวเท่ากันที่ 15 คำ
X_text = pad_sequences(sequences, maxlen=15)
y_text = df2['Sentiment'].values

# ตรวจสอบขนาดข้อมูลก่อนเข้า Model
print(f"Shape of X: {X_text.shape}")
print("Example of cleaned sequence:", X_text[0])

from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
import pickle

# เตรียม X (ปัจจัย) และ y (ผลลัพธ์)
X_ml = df1[['Cuisine', 'Avg_Price', 'Location_Score', 'Social_Checkin']]
y_ml = df1['Status']

# สร้าง Model 3 ตัว(Ensemble)
m1 = RandomForestClassifier(n_estimators=50, random_state=42)
m2 = XGBClassifier(eval_metric='logloss')
m3 = LogisticRegression(max_iter=1000)

# รวมร่างแบบ Voting (ใช้เสียงข้างมาก)
ensemble_model = VotingClassifier(estimators=[('rf', m1), ('xgb', m2), ('lr', m3)], voting='hard')

# --- ขั้นตอน Training ---
ensemble_model.fit(X_ml, y_ml)

# เช็คความแม่นยำ (%)
acc_ensemble = ensemble_model.score(X_ml, y_ml)
print(f"Ensemble Accuracy: {acc_ensemble * 100:.2f}%")

# Save เก็บไว้ใช้
with open('ensemble_model.pkl', 'wb') as f:
    pickle.dump(ensemble_model, f)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout

# สร้างโครงสร้างสมอง AI สำหรับอ่านภาษาไทย
model_nn = Sequential([
    Embedding(input_dim=1000, output_dim=16, input_length=15),
    LSTM(32),
    Dropout(0.2),
    Dense(1, activation='sigmoid') # ผลลัพธ์ 0 หรือ 1 (ดี/แย่)
])

# ตั้งค่าการคำนวณ
model_nn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# --- ขั้นตอน Training (รัน 20 รอบ) ---
model_nn.fit(X_text, y_text, epochs=20, verbose=0)

# เช็คความแม่นยำ (%)
loss, acc_nn = model_nn.evaluate(X_text, y_text, verbose=0)
print(f"2. Neural Network Accuracy: {acc_nn * 100:.2f}%")

# Save เก็บไว้ใช้
model_nn.save('nn_model.h5')